<a href="https://colab.research.google.com/github/Madhu2303a51846/Python-for-DS-LAB-/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create 2D array (5 students × 3 subjects)
marks = np.array([[78, 85, 90],
                  [60, 72, 68],
                  [88, 92, 95],
                  [45, 55, 50],
                  [82, 79, 88]])

print("Marks:\n", marks)

# Stats
print("\nAverage:", marks.mean())
print("Min:", marks.min(), "Max:", marks.max())

# Slicing: marks of 1st 2 students
print("\nMarks of first 2 students:\n", marks[:2])

# Boolean indexing: students scoring >80 in any subject
print("\nStudents scoring above 80:\n", marks[(marks > 80)])

# Reshape for subject-wise analysis (3 subjects × 5 students)
print("\nSubject-wise performance:\n", marks.T)


Marks:
 [[78 85 90]
 [60 72 68]
 [88 92 95]
 [45 55 50]
 [82 79 88]]

Average: 75.13333333333334
Min: 45 Max: 95

Marks of first 2 students:
 [[78 85 90]
 [60 72 68]]

Students scoring above 80:
 [85 90 88 92 95 82 88]

Subject-wise performance:
 [[78 60 88 45 82]
 [85 72 92 55 79]
 [90 68 95 50 88]]


In [2]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "Finance", "Marketing", "IT"],
    "Salary": [48000, 52000, 75000, 46000, 90000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df)

# Filter salary > 50,000
print("\nEmployees with Salary > 50,000:\n", df[df["Salary"] > 50000])

# Sort by salary (descending)
df_sorted = df.sort_values(by="Salary", ascending=False)
print("\nSorted by Salary (desc):\n", df_sorted)

# Add Bonus (10% of salary)
df["Bonus"] = df["Salary"] * 0.10
print("\nWith Bonus Column:\n", df)

# Total expense (Salary + Bonus)
df["Total"] = df["Salary"] + df["Bonus"]
print("\nTotal Salary Expense including Bonus:", df["Total"].sum())

# Save to CSV
df.to_csv("employee_salary_analysis.csv", index=False)
print("\nData saved to 'employee_salary_analysis.csv'")


Original Data:
     ID     Name Department  Salary
0  101    Alice         HR   48000
1  102      Bob         IT   52000
2  103  Charlie    Finance   75000
3  104    David  Marketing   46000
4  105      Eva         IT   90000

Employees with Salary > 50,000:
     ID     Name Department  Salary
1  102      Bob         IT   52000
2  103  Charlie    Finance   75000
4  105      Eva         IT   90000

Sorted by Salary (desc):
     ID     Name Department  Salary
4  105      Eva         IT   90000
2  103  Charlie    Finance   75000
1  102      Bob         IT   52000
0  101    Alice         HR   48000
3  104    David  Marketing   46000

With Bonus Column:
     ID     Name Department  Salary   Bonus
0  101    Alice         HR   48000  4800.0
1  102      Bob         IT   52000  5200.0
2  103  Charlie    Finance   75000  7500.0
3  104    David  Marketing   46000  4600.0
4  105      Eva         IT   90000  9000.0

Total Salary Expense including Bonus: 342100.0

Data saved to 'employee_salary_anal