<a href="https://colab.research.google.com/github/Madhu2303a51846/Python-for-DS-LAB-/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("\nMatrix Addition (A + B):\n", add_result)
print("\nMatrix Subtraction (A - B):\n", sub_result)

row, col = 1, 2
manual_add = A[row, col] + B[row, col]
manual_sub = A[row, col] - B[row, col]

print(f"\nManual verification at element ({row+1}, {col+1}):")
print(f"A[{row},{col}] = {A[row,col]}, B[{row},{col}] = {B[row,col]}")
print(f"Addition check: {A[row,col]} + {B[row,col]} = {manual_add} (matches {add_result[row,col]})")
print(f"Subtraction check: {A[row,col]} - {B[row,col]} = {manual_sub} (matches {sub_result[row,col]})")

print("\nNote on Broadcasting:")
print("Since both matrices are 3x3 of the same shape, broadcasting is NOT required here.")
print("If one matrix had a shape like (1,3), NumPy broadcasting would align it across rows.")


Matrix A:
 [[ 9 10  7]
 [10  3 10]
 [10  7  2]]

Matrix B:
 [[5 9 4]
 [8 6 7]
 [4 6 9]]

Matrix Addition (A + B):
 [[14 19 11]
 [18  9 17]
 [14 13 11]]

Matrix Subtraction (A - B):
 [[ 4  1  3]
 [ 2 -3  3]
 [ 6  1 -7]]

Manual verification at element (2, 3):
A[1,2] = 10, B[1,2] = 7
Addition check: 10 + 7 = 17 (matches 17)
Subtraction check: 10 - 7 = 3 (matches 3)

Note on Broadcasting:
Since both matrices are 3x3 of the same shape, broadcasting is NOT required here.
If one matrix had a shape like (1,3), NumPy broadcasting would align it across rows.
